### getActivityById
GET http://localhost:8083/api/activity/1
Authorization: Basic 0

### getActivityByUserId
GET http://localhost:8083/api/activity
Authorization: Basic 2

### createActivity
POST http://localhost:8083/api/activity
Authorization: Basic 2
{
  "name": "Dancing",
  "kcalPerMinute": 20.0
}

### json
{
  "id": 6,
  "userId": 2,
  "type": null,
  "name": "Weight Training",
  "kcalPerMinute": 2.0
}
