### getActivityById
GET http://localhost:8083/api/activity/1
Authorization: Basic 0

### getActivityByUserId
GET http://localhost:8083/api/activity
Authorization: Basic 2

### createActivity
POST http://localhost:8083/api/activity
Authorization: Basic 2
{
  "name": "Dancing",
  "kcalPerMinute": 20.0
}

### updateActivity
PUT http://localhost:8083/api/activity/8
Authorization: Basic 2
{
  "kcalPerMinute": 30.0
}

### json
{
  "id": 8,
  "userId": 2,
  "type": "USER",
  "name": "Dancing",
  "kcalPerMinute": 30.0
}
